### ISSUE TITLE
It doesn't seem to work as described.

### ISSUE THREAD

**Issue by Boodlyneck** [JimiIT92/BundlesMod#1]
**Describe the bug**
When I left click any item with the bundle, it just switches the items. Placing the bundle down and picking up the item.

**To Reproduce**
1. open inventory
2. pick up bundle
3. left click items in inventory with the bundle

**Expected behavior**
I expected to pick up the bundle with my inventory open and left-click items with the bundle to put them in the bundle.

**Screenshots**

**Minecraft version:** [e.g. 1.16.3]
1.16.3

**Minecraft Forge version:** [e.g. 1.16.3-34.1.16]
34.1.19

**Additional context**
Based on the comment section it seems that a lot of others are having the same issue. I hope you get this working, I'd love to put it in a video.

**Comment by JimiIT92** [comment]
WOW. Boodlyneck here! Holy.... Ok, jokes asides... Yes, it seems like the "production" version of Forge doesn't handle the click event properly, which is crucial for the mod to work. I'm already investigating why this happens, if is just a version issue or there is something else. I hope to release a proper version in a few days

**Comment by JimiIT92** [comment]
The mod should now work properly. I also took the time to refine the mod itself, fixing sounds and adding 2 tags to specify which blocks/items can't go inside the Bundle. I will post a video later today detailing how the Bundle works. As soon as the jar gets approved on Curse you will be able to download the mod. It will sitll be version 1.0 since, well, a proper first version we can say never came out 😅
