### ISSUE TITLE
Game crash when hovering over a bundle.

### ISSUE THREAD

**Issue by John-M87** [JimiIT92/BundlesMod#4]
I'm having an issue where my game will crash whenever I move my mouse over a bundle

1. Open the inventory 
2. Move the mouse over an empty bundle (haven't tested it with anything in them)
3. Have your game crash

1.16.3

forge-1.16.3-34.1.23

This happens in both JEI and the creative inventory. 

Crash report attached
[crash-2020-10-23_16.48.39-client.txt](https://github.com/JimiIT92/BundlesMod/files/5432186/crash-2020-10-23_16.48.39-client.txt)

P.S. looks like a great mod!

**Comment by JimiIT92** [comment]
That's strange, I just tested with that exact version of Forge and got no problem hovering an empty bundle in creative inventory :/ Have you tried updating the Forge version?

**Comment by John-M87** [comment]
I just did, the issue still persists, here's the crash report

[crash-2020-10-24_15.28.28-client.txt](https://github.com/JimiIT92/BundlesMod/files/5433712/crash-2020-10-24_15.28.28-client.txt)

**Comment by JimiIT92** [comment]
From the crash log I assume there is something really strange going on here. Essentially the fornt render method is probably deobfuscated in the "release" version of Forge but not in the dev build... Maybe the two version uses different mappings, and that's why you have this error. However even stranger is that the 1.16.3-34.1.23 version I installed doesn't have this difference, which is really really weird... I will see if I can find this difference and patch it out, but in this situation is really really hard for me to even think about something, because I can't call a method or another based on what the build is (the build won't even compile)

**Comment by Skjolbir** [comment]
same crash here. 1.16.4 forge ver 35.1.7
crash report mentioned fonts

**Comment by Skjolbir** [comment]
downgraded to 1.1, and seems to work just fine. What changes were made between 1.1 and 1.3?

**Comment by JimiIT92** [comment]
Just somme bug fixing. As I said this bug is related to the Forge mappings in release, which although they are the same for some reason there are some differences. I'll see when I'll update the mod if there is a 100% way of avoiding this problem

**Comment by sal-versij** [comment]
I had the same error, then when i tried to download the 1.1 like Skjolbir, i saw that the version that curseforge downloads as latest is for 1.15.2 then goes on to the 1.16.3 so I tried  to download the 1.3 for the 1.16.3 and it worked without a problem

**Comment by moonfather1** [comment]
just to note that bundles 1.3 also crashes on 1.16.5. same stack trace as above.

i hovered over the item in jei recipes (right click the leather item) and the game crashed.

**Comment by JimiIT92** [comment]
Fixed in version 1.4
https://www.curseforge.com/minecraft/mc-mods/bundles-mod/files/3903683
